on: push

jobs:
  #Unit test
  test:
    timeout-minutes: 5
    runs-on: ubuntu-18.04
    steps:
    - name: Install JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13
        java-package: jdk
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: |
          ./gradle
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    - name: Run tests
      run: |
        ./gradlew test
  
  #Jar creation
  jar:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-18.04
    steps:
    - name: Install JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13
        java-package: jdk
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: |
          ./gradle
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    - name: Create Jar
      run: |
        ./gradlew shadowJar
        
    - name: Upload JAR
      uses: actions/upload-artifact@v1
      with:
        name: shadowJar
        path: ./build/libs/gitnarwhal.jar

  #Windows/Linux/MacOS images
  bundle_jre_images:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-18.04
    steps:
    - name: Install JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13
        java-package: jdk
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: |
          ./gradle
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    - name: Bundle JAR with JRE and launcher script
      run: |
        ./gradlew bundle --stacktrace
        
    - name: Upload Windows image
      uses: actions/upload-artifact@v1
      with:
        name: windows_x64_image
        path: ./build/app/windows_x64
        
    - name: Upload Linux image
      uses: actions/upload-artifact@v1
      with:
        name: linux_x64_image
        path: ./build/app/linux_x64

    - name: Upload MacOS image
      uses: actions/upload-artifact@v1
      with:
        name: mac_x64_image
        path: ./build/app/mac_x64
  
  release_windows:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-18.04
    container: fcdev/gitnarwhal:win
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Cache dependancies
      uses: actions/cache@v2
      with:
        path: |
          ./gradle
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build setup.exe
      run: |
        cp -R /root/.wine ~/.wine
        ./gradlew win64installer
        mv ./build/innosetup/Output/mysetup.exe ./build/innosetup/Output/gitnarwhal.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows_x64_installer
        path: ./build/innosetup/Output/gitnarwhal.exe
